# Generated by Django 5.2.5 on 2025-09-15 08:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('AB+', 'AB+'), ('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_conditions', models.TextField()),
                ('family_history', models.TextField()),
                ('previous_surgeries', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_results', models.TextField()),
                ('imaging', models.TextField(blank=True, null=True)),
                ('other_tests', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labtests', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CheckUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('current_diagnosis', models.TextField()),
                ('date_of_checkup', models.DateField()),
                ('blood_pressure', models.CharField(max_length=50)),
                ('heart_rate', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('bmi', models.CharField(max_length=50)),
                ('physical_exam_findings', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_remarks', models.TextField()),
                ('special_warnings', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_disease', models.CharField(max_length=100)),
                ('assigned_doctor', models.CharField(max_length=100)),
                ('prescribed_medications', models.TextField()),
                ('procedures', models.TextField()),
                ('next_followup_date', models.DateField()),
                ('lifestyle_recommendations', models.TextField(blank=True, null=True)),
                ('physiotherapy_advice', models.TextField(blank=True, null=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='patients.checkup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
        ),
    ]
