# Generated by Django 5.2.6 on 2025-09-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_medicalhistory_family_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bmi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='current_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='date_of_checkup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='heart_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
