# Generated by Django 5.2.5 on 2025-09-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_doctor_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='end_date',
        ),
    ]
